### PR TITLE
ENH: add all `latex_symbols` to greek.cson

### PR DESCRIPTION
**Pull request by sglyon**

### CODE REVIEW

**Comment by tpoisot** [comment]
I think it would be better to split the list in different files.

**Comment by sglyon** [comment]
Ok fair enough. I don't see an obvious way to both provide all the functionality and organize it onto separate files.

Any suggestions?

**Comment by tpoisot** [comment]
You can add new `.cson` files under `snippets`, and separate the
different symbols across different files.

[05/19 16:14] Spencer Lyon:

**Comment by sglyon** [comment]
Oh sorry, I understood that. 

What I don't quite see is how to automatically generate an organized (split across multiple files) version of this using the latex_symbols dict defined in Base.REPLCompletions. 

I like generating this file because we can be sure we don't miss any symbols we have access to at the REPL

**Comment by tpoisot** [comment]
You are right. I'll merge.

**Comment by sglyon** [comment]
Ok awesome thanks.

**Pull request merged**
